# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'character_synthesis_mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1566, 765)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.open_xml_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.open_xml_pushButton.setGeometry(QtCore.QRect(10, 10, 160, 32))
        self.open_xml_pushButton.setObjectName("open_xml_pushButton")
        self.open_chars_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.open_chars_pushButton.setGeometry(QtCore.QRect(180, 10, 160, 32))
        self.open_chars_pushButton.setObjectName("open_chars_pushButton")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(20, 80, 311, 191))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 309, 189))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.input_plainTextEdit = QtWidgets.QPlainTextEdit(self.scrollAreaWidgetContents)
        self.input_plainTextEdit.setGeometry(QtCore.QRect(0, 0, 311, 191))
        self.input_plainTextEdit.setObjectName("input_plainTextEdit")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 60, 91, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 290, 111, 16))
        self.label_2.setObjectName("label_2")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_2.setGeometry(QtCore.QRect(20, 310, 311, 191))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 309, 189))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.temp_chars_plainTextEdit = QtWidgets.QPlainTextEdit(self.scrollAreaWidgetContents_2)
        self.temp_chars_plainTextEdit.setGeometry(QtCore.QRect(0, 0, 311, 191))
        self.temp_chars_plainTextEdit.setObjectName("temp_chars_plainTextEdit")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.tempate_generate_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.tempate_generate_pushButton.setGeometry(QtCore.QRect(20, 520, 161, 32))
        self.tempate_generate_pushButton.setObjectName("tempate_generate_pushButton")
        self.synthesis_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.synthesis_pushButton.setGeometry(QtCore.QRect(20, 580, 114, 32))
        self.synthesis_pushButton.setObjectName("synthesis_pushButton")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_3.setGeometry(QtCore.QRect(360, 50, 221, 551))
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 219, 549))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.generated_results_listWidget = QtWidgets.QListWidget(self.scrollAreaWidgetContents_3)
        self.generated_results_listWidget.setGeometry(QtCore.QRect(0, 0, 231, 551))
        self.generated_results_listWidget.setObjectName("generated_results_listWidget")
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(360, 20, 131, 16))
        self.label_3.setObjectName("label_3")
        self.svg_webEngineView = QtWebEngineWidgets.QWebEngineView(self.centralwidget)
        self.svg_webEngineView.setGeometry(QtCore.QRect(620, 390, 300, 300))
        self.svg_webEngineView.setUrl(QtCore.QUrl("about:blank"))
        self.svg_webEngineView.setObjectName("svg_webEngineView")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(740, 30, 59, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(750, 370, 59, 16))
        self.label_5.setObjectName("label_5")
        self.use_last_chars_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.use_last_chars_pushButton.setGeometry(QtCore.QRect(120, 50, 221, 32))
        self.use_last_chars_pushButton.setObjectName("use_last_chars_pushButton")
        self.grayscale_graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.grayscale_graphicsView.setGeometry(QtCore.QRect(620, 50, 300, 300))
        self.grayscale_graphicsView.setObjectName("grayscale_graphicsView")
        self.scrollArea_4 = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_4.setGeometry(QtCore.QRect(940, 50, 611, 641))
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollArea_4.setObjectName("scrollArea_4")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 609, 639))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.xml_webEngineView = QtWebEngineWidgets.QWebEngineView(self.scrollAreaWidgetContents_4)
        self.xml_webEngineView.setGeometry(QtCore.QRect(0, 0, 611, 641))
        self.xml_webEngineView.setUrl(QtCore.QUrl("about:blank"))
        self.xml_webEngineView.setObjectName("xml_webEngineView")
        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1566, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.open_xml_pushButton.setText(_translate("MainWindow", "Load XML dataset"))
        self.open_chars_pushButton.setText(_translate("MainWindow", "Load Template Chars"))
        self.label.setText(_translate("MainWindow", "Input chars:"))
        self.label_2.setText(_translate("MainWindow", "Template chars:"))
        self.tempate_generate_pushButton.setText(_translate("MainWindow", "Generate Templates"))
        self.synthesis_pushButton.setText(_translate("MainWindow", "Synthesis"))
        self.label_3.setText(_translate("MainWindow", "Generated Results:"))
        self.label_4.setText(_translate("MainWindow", "Grayscale"))
        self.label_5.setText(_translate("MainWindow", "SVG"))
        self.use_last_chars_pushButton.setText(_translate("MainWindow", "Use last chars"))

from PyQt5 import QtWebEngineWidgets
