# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'character_synthesis_mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1877, 965)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.open_xml_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.open_xml_pushButton.setGeometry(QtCore.QRect(10, 10, 160, 32))
        self.open_xml_pushButton.setObjectName("open_xml_pushButton")
        self.open_chars_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.open_chars_pushButton.setGeometry(QtCore.QRect(180, 10, 160, 32))
        self.open_chars_pushButton.setObjectName("open_chars_pushButton")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(20, 80, 311, 191))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 309, 189))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.input_plainTextEdit = QtWidgets.QPlainTextEdit(self.scrollAreaWidgetContents)
        self.input_plainTextEdit.setGeometry(QtCore.QRect(0, 0, 311, 191))
        self.input_plainTextEdit.setObjectName("input_plainTextEdit")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 60, 91, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 290, 111, 16))
        self.label_2.setObjectName("label_2")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_2.setGeometry(QtCore.QRect(20, 310, 311, 191))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 309, 189))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.temp_chars_plainTextEdit = QtWidgets.QPlainTextEdit(self.scrollAreaWidgetContents_2)
        self.temp_chars_plainTextEdit.setGeometry(QtCore.QRect(0, 0, 311, 191))
        self.temp_chars_plainTextEdit.setObjectName("temp_chars_plainTextEdit")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.tempate_generate_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.tempate_generate_pushButton.setGeometry(QtCore.QRect(20, 520, 161, 32))
        self.tempate_generate_pushButton.setObjectName("tempate_generate_pushButton")
        self.synthesis_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.synthesis_pushButton.setGeometry(QtCore.QRect(20, 620, 114, 32))
        self.synthesis_pushButton.setObjectName("synthesis_pushButton")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_3.setGeometry(QtCore.QRect(360, 50, 191, 551))
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 189, 549))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.generated_results_listWidget = QtWidgets.QListWidget(self.scrollAreaWidgetContents_3)
        self.generated_results_listWidget.setGeometry(QtCore.QRect(0, 0, 191, 551))
        self.generated_results_listWidget.setObjectName("generated_results_listWidget")
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(390, 20, 131, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(740, 30, 131, 16))
        self.label_4.setObjectName("label_4")
        self.use_last_chars_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.use_last_chars_pushButton.setGeometry(QtCore.QRect(120, 50, 221, 32))
        self.use_last_chars_pushButton.setObjectName("use_last_chars_pushButton")
        self.grayscale_graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.grayscale_graphicsView.setGeometry(QtCore.QRect(1120, 50, 500, 500))
        self.grayscale_graphicsView.setObjectName("grayscale_graphicsView")
        self.scrollArea_4 = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_4.setGeometry(QtCore.QRect(1650, 30, 200, 380))
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollArea_4.setObjectName("scrollArea_4")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 198, 378))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.similar_bs_treeView = QtWidgets.QTreeView(self.scrollAreaWidgetContents_4)
        self.similar_bs_treeView.setGeometry(QtCore.QRect(0, 0, 200, 380))
        self.similar_bs_treeView.setObjectName("similar_bs_treeView")
        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_4)
        self.scrollArea_5 = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_5.setGeometry(QtCore.QRect(1650, 450, 200, 450))
        self.scrollArea_5.setWidgetResizable(True)
        self.scrollArea_5.setObjectName("scrollArea_5")
        self.scrollAreaWidgetContents_5 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 198, 448))
        self.scrollAreaWidgetContents_5.setObjectName("scrollAreaWidgetContents_5")
        self.similar_stroke_treeView = QtWidgets.QTreeView(self.scrollAreaWidgetContents_5)
        self.similar_stroke_treeView.setGeometry(QtCore.QRect(0, 0, 200, 450))
        self.similar_stroke_treeView.setObjectName("similar_stroke_treeView")
        self.scrollArea_5.setWidget(self.scrollAreaWidgetContents_5)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(1690, 10, 101, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(1730, 430, 71, 16))
        self.label_6.setObjectName("label_6")
        self.scrollArea_6 = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_6.setGeometry(QtCore.QRect(20, 650, 411, 241))
        self.scrollArea_6.setWidgetResizable(True)
        self.scrollArea_6.setObjectName("scrollArea_6")
        self.scrollAreaWidgetContents_6 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_6.setGeometry(QtCore.QRect(0, 0, 409, 239))
        self.scrollAreaWidgetContents_6.setObjectName("scrollAreaWidgetContents_6")
        self.similar_chars_bs_treeView = QtWidgets.QTreeView(self.scrollAreaWidgetContents_6)
        self.similar_chars_bs_treeView.setGeometry(QtCore.QRect(0, 0, 411, 241))
        self.similar_chars_bs_treeView.setObjectName("similar_chars_bs_treeView")
        self.scrollArea_6.setWidget(self.scrollAreaWidgetContents_6)
        self.svg_extract_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.svg_extract_pushButton.setGeometry(QtCore.QRect(210, 620, 114, 32))
        self.svg_extract_pushButton.setObjectName("svg_extract_pushButton")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 560, 311, 54))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.bs_threshold_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.bs_threshold_lineEdit.setObjectName("bs_threshold_lineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.bs_threshold_lineEdit)
        self.stroke_threshold_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.stroke_threshold_lineEdit.setObjectName("stroke_threshold_lineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.stroke_threshold_lineEdit)
        self.src_graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.src_graphicsView.setGeometry(QtCore.QRect(570, 50, 500, 500))
        self.src_graphicsView.setObjectName("src_graphicsView")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(1270, 30, 131, 16))
        self.label_9.setObjectName("label_9")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1877, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.open_xml_pushButton.setText(_translate("MainWindow", "Load XML dataset"))
        self.open_chars_pushButton.setText(_translate("MainWindow", "Load Template Chars"))
        self.label.setText(_translate("MainWindow", "Input chars:"))
        self.label_2.setText(_translate("MainWindow", "Template chars:"))
        self.tempate_generate_pushButton.setText(_translate("MainWindow", "Generate Templates"))
        self.synthesis_pushButton.setText(_translate("MainWindow", "Synthesis"))
        self.label_3.setText(_translate("MainWindow", "Generated Results:"))
        self.label_4.setText(_translate("MainWindow", "True image"))
        self.use_last_chars_pushButton.setText(_translate("MainWindow", "Use last chars"))
        self.label_5.setText(_translate("MainWindow", "Basic radicals:"))
        self.label_6.setText(_translate("MainWindow", "Strokes:"))
        self.svg_extract_pushButton.setText(_translate("MainWindow", "Extract_SVG"))
        self.label_7.setText(_translate("MainWindow", "Basic Radical threshold:"))
        self.label_8.setText(_translate("MainWindow", "Stroke threshold:"))
        self.label_9.setText(_translate("MainWindow", "Generated image"))

