# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'xml_query_edit_mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1641, 990)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(20, 10, 1611, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(20, 40, 1611, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.open_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.open_pushButton.setGeometry(QtCore.QRect(40, 20, 114, 32))
        self.open_pushButton.setObjectName("open_pushButton")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(230, 20, 471, 33))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.search_lineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.search_lineEdit.setObjectName("search_lineEdit")
        self.horizontalLayout.addWidget(self.search_lineEdit)
        self.search_pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.search_pushButton.setObjectName("search_pushButton")
        self.horizontalLayout.addWidget(self.search_pushButton)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(883, 50, 20, 881))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.save_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.save_pushButton.setGeometry(QtCore.QRect(700, 880, 114, 32))
        self.save_pushButton.setObjectName("save_pushButton")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(890, 50, 741, 881))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 739, 879))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.xml_main_webEngineView = QtWebEngineWidgets.QWebEngineView(self.scrollAreaWidgetContents)
        self.xml_main_webEngineView.setGeometry(QtCore.QRect(0, 0, 741, 881))
        self.xml_main_webEngineView.setUrl(QtCore.QUrl("about:blank"))
        self.xml_main_webEngineView.setObjectName("xml_main_webEngineView")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(20, 80, 691, 21))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 70, 59, 16))
        self.label_2.setObjectName("label_2")
        self.unicode_label = QtWidgets.QLabel(self.centralwidget)
        self.unicode_label.setGeometry(QtCore.QRect(120, 70, 59, 16))
        self.unicode_label.setObjectName("unicode_label")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(210, 70, 59, 16))
        self.label_3.setObjectName("label_3")
        self.char_label = QtWidgets.QLabel(self.centralwidget)
        self.char_label.setGeometry(QtCore.QRect(260, 70, 59, 16))
        self.char_label.setObjectName("char_label")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 100, 231, 105))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.type_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.type_lineEdit.setObjectName("type_lineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.type_lineEdit)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.struct_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.struct_lineEdit.setObjectName("struct_lineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.struct_lineEdit)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.key_radical_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.key_radical_lineEdit.setObjectName("key_radical_lineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.key_radical_lineEdit)
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(20, 220, 351, 201))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_9 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.label_10 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_10.setObjectName("label_10")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.bs_0_id_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.bs_0_id_lineEdit.setObjectName("bs_0_id_lineEdit")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.bs_0_id_lineEdit)
        self.label_11 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_11.setObjectName("label_11")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.bs_0_tag_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.bs_0_tag_lineEdit.setObjectName("bs_0_tag_lineEdit")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.bs_0_tag_lineEdit)
        self.label_12 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_12.setObjectName("label_12")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.bs_0_strokes_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.bs_0_strokes_lineEdit.setObjectName("bs_0_strokes_lineEdit")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.bs_0_strokes_lineEdit)
        self.label_13 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_13.setObjectName("label_13")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.bs_0_similar_tag_plainTextEdit = QtWidgets.QPlainTextEdit(self.formLayoutWidget_2)
        self.bs_0_similar_tag_plainTextEdit.setObjectName("bs_0_similar_tag_plainTextEdit")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.bs_0_similar_tag_plainTextEdit)
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(280, 100, 341, 101))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.stroke_count_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.stroke_count_lineEdit.setObjectName("stroke_count_lineEdit")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.stroke_count_lineEdit)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_8.setObjectName("label_8")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.stroke_order_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.stroke_order_lineEdit.setObjectName("stroke_order_lineEdit")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.stroke_order_lineEdit)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_7.setObjectName("label_7")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.formLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(420, 220, 351, 201))
        self.formLayoutWidget_4.setObjectName("formLayoutWidget_4")
        self.formLayout_4 = QtWidgets.QFormLayout(self.formLayoutWidget_4)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_14 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.label_14.setObjectName("label_14")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.label_15 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.label_15.setObjectName("label_15")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.bs_1_id_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.bs_1_id_lineEdit.setObjectName("bs_1_id_lineEdit")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.bs_1_id_lineEdit)
        self.label_16 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.label_16.setObjectName("label_16")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.bs_1_tag_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.bs_1_tag_lineEdit.setObjectName("bs_1_tag_lineEdit")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.bs_1_tag_lineEdit)
        self.label_17 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.label_17.setObjectName("label_17")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.bs_1_strokes_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.bs_1_strokes_lineEdit.setObjectName("bs_1_strokes_lineEdit")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.bs_1_strokes_lineEdit)
        self.label_18 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.label_18.setObjectName("label_18")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.bs_1_similar_tag_plainTextEdit = QtWidgets.QPlainTextEdit(self.formLayoutWidget_4)
        self.bs_1_similar_tag_plainTextEdit.setObjectName("bs_1_similar_tag_plainTextEdit")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.bs_1_similar_tag_plainTextEdit)
        self.formLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget_5.setGeometry(QtCore.QRect(20, 440, 351, 201))
        self.formLayoutWidget_5.setObjectName("formLayoutWidget_5")
        self.formLayout_5 = QtWidgets.QFormLayout(self.formLayoutWidget_5)
        self.formLayout_5.setContentsMargins(0, 0, 0, 0)
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_19 = QtWidgets.QLabel(self.formLayoutWidget_5)
        self.label_19.setObjectName("label_19")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.label_20 = QtWidgets.QLabel(self.formLayoutWidget_5)
        self.label_20.setObjectName("label_20")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.bs_2_id_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_5)
        self.bs_2_id_lineEdit.setObjectName("bs_2_id_lineEdit")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.bs_2_id_lineEdit)
        self.label_21 = QtWidgets.QLabel(self.formLayoutWidget_5)
        self.label_21.setObjectName("label_21")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self.bs_2_tag_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_5)
        self.bs_2_tag_lineEdit.setObjectName("bs_2_tag_lineEdit")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.bs_2_tag_lineEdit)
        self.label_22 = QtWidgets.QLabel(self.formLayoutWidget_5)
        self.label_22.setObjectName("label_22")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_22)
        self.bs_2_strokes_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_5)
        self.bs_2_strokes_lineEdit.setObjectName("bs_2_strokes_lineEdit")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.bs_2_strokes_lineEdit)
        self.label_23 = QtWidgets.QLabel(self.formLayoutWidget_5)
        self.label_23.setObjectName("label_23")
        self.formLayout_5.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_23)
        self.bs_2_similar_tag_plainTextEdit = QtWidgets.QPlainTextEdit(self.formLayoutWidget_5)
        self.bs_2_similar_tag_plainTextEdit.setObjectName("bs_2_similar_tag_plainTextEdit")
        self.formLayout_5.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.bs_2_similar_tag_plainTextEdit)
        self.formLayoutWidget_6 = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget_6.setGeometry(QtCore.QRect(420, 440, 351, 201))
        self.formLayoutWidget_6.setObjectName("formLayoutWidget_6")
        self.formLayout_6 = QtWidgets.QFormLayout(self.formLayoutWidget_6)
        self.formLayout_6.setContentsMargins(0, 0, 0, 0)
        self.formLayout_6.setObjectName("formLayout_6")
        self.label_24 = QtWidgets.QLabel(self.formLayoutWidget_6)
        self.label_24.setObjectName("label_24")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_24)
        self.label_25 = QtWidgets.QLabel(self.formLayoutWidget_6)
        self.label_25.setObjectName("label_25")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_25)
        self.bs_3_id_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_6)
        self.bs_3_id_lineEdit.setObjectName("bs_3_id_lineEdit")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.bs_3_id_lineEdit)
        self.label_26 = QtWidgets.QLabel(self.formLayoutWidget_6)
        self.label_26.setObjectName("label_26")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_26)
        self.bs_3_tag_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_6)
        self.bs_3_tag_lineEdit.setObjectName("bs_3_tag_lineEdit")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.bs_3_tag_lineEdit)
        self.label_27 = QtWidgets.QLabel(self.formLayoutWidget_6)
        self.label_27.setObjectName("label_27")
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_27)
        self.bs_3_strokes_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_6)
        self.bs_3_strokes_lineEdit.setObjectName("bs_3_strokes_lineEdit")
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.bs_3_strokes_lineEdit)
        self.label_28 = QtWidgets.QLabel(self.formLayoutWidget_6)
        self.label_28.setObjectName("label_28")
        self.formLayout_6.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_28)
        self.bs_3_similar_tag_plainTextEdit = QtWidgets.QPlainTextEdit(self.formLayoutWidget_6)
        self.bs_3_similar_tag_plainTextEdit.setObjectName("bs_3_similar_tag_plainTextEdit")
        self.formLayout_6.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.bs_3_similar_tag_plainTextEdit)
        self.formLayoutWidget_7 = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget_7.setGeometry(QtCore.QRect(20, 660, 351, 201))
        self.formLayoutWidget_7.setObjectName("formLayoutWidget_7")
        self.formLayout_7 = QtWidgets.QFormLayout(self.formLayoutWidget_7)
        self.formLayout_7.setContentsMargins(0, 0, 0, 0)
        self.formLayout_7.setObjectName("formLayout_7")
        self.label_29 = QtWidgets.QLabel(self.formLayoutWidget_7)
        self.label_29.setObjectName("label_29")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_29)
        self.label_30 = QtWidgets.QLabel(self.formLayoutWidget_7)
        self.label_30.setObjectName("label_30")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_30)
        self.bs_4_id_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_7)
        self.bs_4_id_lineEdit.setObjectName("bs_4_id_lineEdit")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.bs_4_id_lineEdit)
        self.label_31 = QtWidgets.QLabel(self.formLayoutWidget_7)
        self.label_31.setObjectName("label_31")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_31)
        self.bs_4_tag_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_7)
        self.bs_4_tag_lineEdit.setObjectName("bs_4_tag_lineEdit")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.bs_4_tag_lineEdit)
        self.label_32 = QtWidgets.QLabel(self.formLayoutWidget_7)
        self.label_32.setObjectName("label_32")
        self.formLayout_7.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_32)
        self.bs_4_strokes_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_7)
        self.bs_4_strokes_lineEdit.setObjectName("bs_4_strokes_lineEdit")
        self.formLayout_7.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.bs_4_strokes_lineEdit)
        self.label_33 = QtWidgets.QLabel(self.formLayoutWidget_7)
        self.label_33.setObjectName("label_33")
        self.formLayout_7.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_33)
        self.bs_4_similar_tag_plainTextEdit = QtWidgets.QPlainTextEdit(self.formLayoutWidget_7)
        self.bs_4_similar_tag_plainTextEdit.setObjectName("bs_4_similar_tag_plainTextEdit")
        self.formLayout_7.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.bs_4_similar_tag_plainTextEdit)
        self.formLayoutWidget_8 = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget_8.setGeometry(QtCore.QRect(420, 660, 351, 201))
        self.formLayoutWidget_8.setObjectName("formLayoutWidget_8")
        self.formLayout_8 = QtWidgets.QFormLayout(self.formLayoutWidget_8)
        self.formLayout_8.setContentsMargins(0, 0, 0, 0)
        self.formLayout_8.setObjectName("formLayout_8")
        self.label_34 = QtWidgets.QLabel(self.formLayoutWidget_8)
        self.label_34.setObjectName("label_34")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_34)
        self.label_35 = QtWidgets.QLabel(self.formLayoutWidget_8)
        self.label_35.setObjectName("label_35")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_35)
        self.bs_5_id_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_8)
        self.bs_5_id_lineEdit.setObjectName("bs_5_id_lineEdit")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.bs_5_id_lineEdit)
        self.label_36 = QtWidgets.QLabel(self.formLayoutWidget_8)
        self.label_36.setObjectName("label_36")
        self.formLayout_8.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_36)
        self.bs_5_tag_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_8)
        self.bs_5_tag_lineEdit.setObjectName("bs_5_tag_lineEdit")
        self.formLayout_8.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.bs_5_tag_lineEdit)
        self.label_37 = QtWidgets.QLabel(self.formLayoutWidget_8)
        self.label_37.setObjectName("label_37")
        self.formLayout_8.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_37)
        self.bs_5_strokes_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_8)
        self.bs_5_strokes_lineEdit.setObjectName("bs_5_strokes_lineEdit")
        self.formLayout_8.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.bs_5_strokes_lineEdit)
        self.label_38 = QtWidgets.QLabel(self.formLayoutWidget_8)
        self.label_38.setObjectName("label_38")
        self.formLayout_8.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_38)
        self.bs_5_similar_tag_plainTextEdit = QtWidgets.QPlainTextEdit(self.formLayoutWidget_8)
        self.bs_5_similar_tag_plainTextEdit.setObjectName("bs_5_similar_tag_plainTextEdit")
        self.formLayout_8.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.bs_5_similar_tag_plainTextEdit)
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(27, 199, 751, 31))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(20, 860, 751, 31))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_7.setGeometry(QtCore.QRect(380, 210, 20, 661))
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtWidgets.QFrame(self.centralwidget)
        self.line_8.setGeometry(QtCore.QRect(20, 415, 751, 31))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.line_9 = QtWidgets.QFrame(self.centralwidget)
        self.line_9.setGeometry(QtCore.QRect(20, 630, 751, 41))
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1641, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "XML Query & Edit App"))
        self.open_pushButton.setText(_translate("MainWindow", "Open"))
        self.label.setText(_translate("MainWindow", "Char="))
        self.search_pushButton.setText(_translate("MainWindow", "Search"))
        self.save_pushButton.setText(_translate("MainWindow", "Save"))
        self.label_2.setText(_translate("MainWindow", "Unicode:"))
        self.unicode_label.setText(_translate("MainWindow", "0000"))
        self.label_3.setText(_translate("MainWindow", "Char: "))
        self.char_label.setText(_translate("MainWindow", "一"))
        self.label_4.setText(_translate("MainWindow", "TYPE:"))
        self.label_5.setText(_translate("MainWindow", "STRUCTURE: "))
        self.label_6.setText(_translate("MainWindow", "KEY_RADICAL:"))
        self.label_9.setText(_translate("MainWindow", "Basic Radical 1:"))
        self.label_10.setText(_translate("MainWindow", "ID:"))
        self.label_11.setText(_translate("MainWindow", "TAG:"))
        self.label_12.setText(_translate("MainWindow", "Strokes:"))
        self.label_13.setText(_translate("MainWindow", "SIMILAR_TAG:"))
        self.label_8.setText(_translate("MainWindow", "STROKE_ORDER:"))
        self.label_7.setText(_translate("MainWindow", "STROKE_COUNT:"))
        self.label_14.setText(_translate("MainWindow", "Basic Radical 2:"))
        self.label_15.setText(_translate("MainWindow", "ID:"))
        self.label_16.setText(_translate("MainWindow", "TAG:"))
        self.label_17.setText(_translate("MainWindow", "Strokes:"))
        self.label_18.setText(_translate("MainWindow", "SIMILAR_TAG:"))
        self.label_19.setText(_translate("MainWindow", "Basic Radical 3:"))
        self.label_20.setText(_translate("MainWindow", "ID:"))
        self.label_21.setText(_translate("MainWindow", "TAG:"))
        self.label_22.setText(_translate("MainWindow", "Strokes:"))
        self.label_23.setText(_translate("MainWindow", "SIMILAR_TAG:"))
        self.label_24.setText(_translate("MainWindow", "Basic Radical 4:"))
        self.label_25.setText(_translate("MainWindow", "ID:"))
        self.label_26.setText(_translate("MainWindow", "TAG:"))
        self.label_27.setText(_translate("MainWindow", "Strokes:"))
        self.label_28.setText(_translate("MainWindow", "SIMILAR_TAG:"))
        self.label_29.setText(_translate("MainWindow", "Basic Radical 5:"))
        self.label_30.setText(_translate("MainWindow", "ID:"))
        self.label_31.setText(_translate("MainWindow", "TAG:"))
        self.label_32.setText(_translate("MainWindow", "Strokes:"))
        self.label_33.setText(_translate("MainWindow", "SIMILAR_TAG:"))
        self.label_34.setText(_translate("MainWindow", "Basic Radical 6:"))
        self.label_35.setText(_translate("MainWindow", "ID:"))
        self.label_36.setText(_translate("MainWindow", "TAG:"))
        self.label_37.setText(_translate("MainWindow", "Strokes:"))
        self.label_38.setText(_translate("MainWindow", "SIMILAR_TAG:"))

from PyQt5 import QtWebEngineWidgets
