# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1200, 820)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(360, 10, 831, 731))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 829, 729))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.image_gw = QtWidgets.QGraphicsView(self.scrollAreaWidgetContents)
        self.image_gw.setGeometry(QtCore.QRect(0, 0, 901, 731))
        self.image_gw.setObjectName("image_gw")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 20, 241, 16))
        self.label.setObjectName("label")
        self.text_content_edit = QtWidgets.QTextEdit(self.centralwidget)
        self.text_content_edit.setGeometry(QtCore.QRect(20, 50, 311, 121))
        self.text_content_edit.setPlaceholderText("")
        self.text_content_edit.setObjectName("text_content_edit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 300, 71, 16))
        self.label_2.setObjectName("label_2")
        self.template_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.template_comboBox.setGeometry(QtCore.QRect(120, 290, 211, 32))
        self.template_comboBox.setObjectName("template_comboBox")
        self.template_comboBox.addItem("")
        self.template_comboBox.addItem("")
        self.template_comboBox.addItem("")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 390, 91, 16))
        self.label_3.setObjectName("label_3")
        self.word_space_slider = QtWidgets.QSlider(self.centralwidget)
        self.word_space_slider.setGeometry(QtCore.QRect(130, 390, 160, 22))
        self.word_space_slider.setOrientation(QtCore.Qt.Horizontal)
        self.word_space_slider.setObjectName("word_space_slider")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 430, 111, 16))
        self.label_4.setObjectName("label_4")
        self.column_space_slider = QtWidgets.QSlider(self.centralwidget)
        self.column_space_slider.setGeometry(QtCore.QRect(130, 430, 160, 22))
        self.column_space_slider.setOrientation(QtCore.Qt.Horizontal)
        self.column_space_slider.setObjectName("column_space_slider")
        self.generate_btn = QtWidgets.QPushButton(self.centralwidget)
        self.generate_btn.setGeometry(QtCore.QRect(30, 510, 171, 32))
        self.generate_btn.setObjectName("generate_btn")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(30, 260, 59, 16))
        self.label_5.setObjectName("label_5")
        self.font_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.font_comboBox.setGeometry(QtCore.QRect(120, 250, 211, 32))
        self.font_comboBox.setObjectName("font_comboBox")
        self.font_comboBox.addItem("")
        self.font_comboBox.addItem("")
        self.font_comboBox.addItem("")
        self.set_dataset_path_btn = QtWidgets.QPushButton(self.centralwidget)
        self.set_dataset_path_btn.setGeometry(QtCore.QRect(20, 200, 311, 32))
        self.set_dataset_path_btn.setObjectName("set_dataset_path_btn")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(30, 350, 141, 16))
        self.label_6.setObjectName("label_6")
        self.num_per_colu_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.num_per_colu_lineEdit.setGeometry(QtCore.QRect(170, 350, 151, 21))
        self.num_per_colu_lineEdit.setObjectName("num_per_colu_lineEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Text Contents:"))
        self.label_2.setText(_translate("MainWindow", "Templates:"))
        self.template_comboBox.setItemText(0, _translate("MainWindow", "斗方"))
        self.template_comboBox.setItemText(1, _translate("MainWindow", "扇面"))
        self.template_comboBox.setItemText(2, _translate("MainWindow", "对联"))
        self.label_3.setText(_translate("MainWindow", "Word space:"))
        self.label_4.setText(_translate("MainWindow", "Column Space："))
        self.generate_btn.setText(_translate("MainWindow", "Generate Calligraphy"))
        self.label_5.setText(_translate("MainWindow", "Font:"))
        self.font_comboBox.setItemText(0, _translate("MainWindow", "楷体"))
        self.font_comboBox.setItemText(1, _translate("MainWindow", "宋体"))
        self.font_comboBox.setItemText(2, _translate("MainWindow", "启功体"))
        self.set_dataset_path_btn.setText(_translate("MainWindow", "set Dataset path"))
        self.label_6.setText(_translate("MainWindow", "Number per Column："))
        self.num_per_colu_lineEdit.setPlaceholderText(_translate("MainWindow", "5"))

