# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1243, 1074)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 250, 331))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.set_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.set_pushButton.setObjectName("set_pushButton")
        self.verticalLayout.addWidget(self.set_pushButton)
        self.input_textEdit = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.input_textEdit.setObjectName("input_textEdit")
        self.verticalLayout.addWidget(self.input_textEdit)
        self.generate_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.generate_pushButton.setObjectName("generate_pushButton")
        self.verticalLayout.addWidget(self.generate_pushButton)
        self.svg_extraction_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.svg_extraction_pushButton.setObjectName("svg_extraction_pushButton")
        self.verticalLayout.addWidget(self.svg_extraction_pushButton)
        self.result_graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.result_graphicsView.setGeometry(QtCore.QRect(330, 20, 300, 300))
        self.result_graphicsView.setObjectName("result_graphicsView")
        self.chars_listView = QtWidgets.QListView(self.centralwidget)
        self.chars_listView.setGeometry(QtCore.QRect(680, 20, 231, 341))
        self.chars_listView.setObjectName("chars_listView")
        self.stroke_graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.stroke_graphicsView.setGeometry(QtCore.QRect(330, 370, 300, 300))
        self.stroke_graphicsView.setObjectName("stroke_graphicsView")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 500, 131, 16))
        self.label.setObjectName("label")
        self.stroke_info_label = QtWidgets.QLabel(self.centralwidget)
        self.stroke_info_label.setGeometry(QtCore.QRect(20, 510, 241, 111))
        self.stroke_info_label.setObjectName("stroke_info_label")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(930, 400, 291, 621))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 289, 619))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.target_strokes_treeView = QtWidgets.QTreeView(self.scrollAreaWidgetContents)
        self.target_strokes_treeView.setGeometry(QtCore.QRect(0, 0, 291, 641))
        self.target_strokes_treeView.setObjectName("target_strokes_treeView")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.basic_radical_graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.basic_radical_graphicsView.setGeometry(QtCore.QRect(330, 700, 300, 300))
        self.basic_radical_graphicsView.setObjectName("basic_radical_graphicsView")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(430, 0, 111, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(740, 0, 91, 16))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(440, 350, 91, 16))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(420, 680, 131, 20))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(1020, 380, 91, 16))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_2.setGeometry(QtCore.QRect(930, 20, 291, 341))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 289, 339))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.target_basic_radicals_treeView = QtWidgets.QTreeView(self.scrollAreaWidgetContents_2)
        self.target_basic_radicals_treeView.setGeometry(QtCore.QRect(0, 0, 291, 341))
        self.target_basic_radicals_treeView.setObjectName("target_basic_radicals_treeView")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(1020, 0, 91, 16))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(230, -10, 71, 1021))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(660, -10, 20, 1031))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(270, 330, 401, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(270, 670, 401, 16))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(880, 0, 81, 1021))
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(920, 360, 321, 20))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(20, 360, 241, 91))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.radioButton_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.radioButton_layout.setContentsMargins(0, 0, 0, 0)
        self.radioButton_layout.setObjectName("radioButton_layout")
        self.radioButton_jiugong_grid = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.radioButton_jiugong_grid.setChecked(True)
        self.radioButton_jiugong_grid.setObjectName("radioButton_jiugong_grid")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.radioButton_jiugong_grid)
        self.radioButton_layout.addWidget(self.radioButton_jiugong_grid)
        self.radioButton_mizi_grid = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.radioButton_mizi_grid.setChecked(False)
        self.radioButton_mizi_grid.setObjectName("radioButton_mizi_grid")
        self.buttonGroup.addButton(self.radioButton_mizi_grid)
        self.radioButton_layout.addWidget(self.radioButton_mizi_grid)
        self.radioButton_tianzi_grid = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.radioButton_tianzi_grid.setObjectName("radioButton_tianzi_grid")
        self.buttonGroup.addButton(self.radioButton_tianzi_grid)
        self.radioButton_layout.addWidget(self.radioButton_tianzi_grid)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1243, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CalligraphyGenerationByBasicRadicalAndStroke"))
        self.set_pushButton.setText(_translate("MainWindow", "Load basic radical & stroke Dataset"))
        self.generate_pushButton.setText(_translate("MainWindow", "Generate"))
        self.svg_extraction_pushButton.setText(_translate("MainWindow", "SVG extraction"))
        self.label.setText(_translate("MainWindow", "Stroke Information:"))
        self.stroke_info_label.setText(_translate("MainWindow", "TextLabel"))
        self.label_2.setText(_translate("MainWindow", "Generated Result"))
        self.label_3.setText(_translate("MainWindow", "Characters"))
        self.label_4.setText(_translate("MainWindow", "Select Stroke"))
        self.label_5.setText(_translate("MainWindow", "Select basic radical"))
        self.label_6.setText(_translate("MainWindow", "Strokes"))
        self.label_7.setText(_translate("MainWindow", "Basic radicals"))
        self.radioButton_jiugong_grid.setText(_translate("MainWindow", "九宫格"))
        self.radioButton_mizi_grid.setText(_translate("MainWindow", "米字格"))
        self.radioButton_tianzi_grid.setText(_translate("MainWindow", "田字格"))

